image:
  file: Dockerfile

tasks:
  - init: |
      echo "Initializing workspace..."
      # Create a virtual hard disk (20GB) for Windows installation
      qemu-img create -f qcow2 win10.img 20G
      # Download Windows 10 ISO (replace with direct link if you have one)
      wget -O windows10.iso "https://software-download.microsoft.com/pr/Win10_21H2_English_x64.iso"
  - command: |
      echo "Starting QEMU and noVNC..."
      # Start noVNC server
      websockify --web=/usr/share/novnc/ 6080 :5900 &
      # Start QEMU with the Windows 10 ISO
      qemu-system-x86_64 \
        -m 4096 \
        -smp 2 \
        -vnc :0 \
        -cdrom windows10.iso \
        -boot d \
        -hda win10.img \
        -enable-kvm
